/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseInvoicesIdEditRouteImport } from './routes/purchase-invoices.$id.edit'
import { Route as ApiReportsGlAnalysisRouteImport } from './routes/api/reports/gl-analysis'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as ApiBillsUpdateRouteImport } from './routes/api/bills/update'
import { Route as ApiBillsCreateRouteImport } from './routes/api/bills/create'
import { Route as ApiAuthDevConnectRouteImport } from './routes/api/auth/dev-connect'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseInvoicesIdEditRoute = PurchaseInvoicesIdEditRouteImport.update({
  id: '/purchase-invoices/$id/edit',
  path: '/purchase-invoices/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsGlAnalysisRoute = ApiReportsGlAnalysisRouteImport.update({
  id: '/api/reports/gl-analysis',
  path: '/api/reports/gl-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsUpdateRoute = ApiBillsUpdateRouteImport.update({
  id: '/api/bills/update',
  path: '/api/bills/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsCreateRoute = ApiBillsCreateRouteImport.update({
  id: '/api/bills/create',
  path: '/api/bills/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevConnectRoute = ApiAuthDevConnectRouteImport.update({
  id: '/api/auth/dev-connect',
  path: '/api/auth/dev-connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/bills/create': typeof ApiBillsCreateRoute
  '/api/bills/update': typeof ApiBillsUpdateRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/reports/gl-analysis': typeof ApiReportsGlAnalysisRoute
  '/purchase-invoices/$id/edit': typeof PurchaseInvoicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/bills/create': typeof ApiBillsCreateRoute
  '/api/bills/update': typeof ApiBillsUpdateRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/reports/gl-analysis': typeof ApiReportsGlAnalysisRoute
  '/purchase-invoices/$id/edit': typeof PurchaseInvoicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/history': typeof HistoryRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/bills/create': typeof ApiBillsCreateRoute
  '/api/bills/update': typeof ApiBillsUpdateRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/reports/gl-analysis': typeof ApiReportsGlAnalysisRoute
  '/purchase-invoices/$id/edit': typeof PurchaseInvoicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-login'
    | '/history'
    | '/reports'
    | '/settings'
    | '/api/auth/dev-connect'
    | '/api/bills/create'
    | '/api/bills/update'
    | '/api/proxy/$'
    | '/api/reports/gl-analysis'
    | '/purchase-invoices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-login'
    | '/history'
    | '/reports'
    | '/settings'
    | '/api/auth/dev-connect'
    | '/api/bills/create'
    | '/api/bills/update'
    | '/api/proxy/$'
    | '/api/reports/gl-analysis'
    | '/purchase-invoices/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dev-login'
    | '/history'
    | '/reports'
    | '/settings'
    | '/api/auth/dev-connect'
    | '/api/bills/create'
    | '/api/bills/update'
    | '/api/proxy/$'
    | '/api/reports/gl-analysis'
    | '/purchase-invoices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevLoginRoute: typeof DevLoginRoute
  HistoryRoute: typeof HistoryRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthDevConnectRoute: typeof ApiAuthDevConnectRoute
  ApiBillsCreateRoute: typeof ApiBillsCreateRoute
  ApiBillsUpdateRoute: typeof ApiBillsUpdateRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiReportsGlAnalysisRoute: typeof ApiReportsGlAnalysisRoute
  PurchaseInvoicesIdEditRoute: typeof PurchaseInvoicesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-invoices/$id/edit': {
      id: '/purchase-invoices/$id/edit'
      path: '/purchase-invoices/$id/edit'
      fullPath: '/purchase-invoices/$id/edit'
      preLoaderRoute: typeof PurchaseInvoicesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/gl-analysis': {
      id: '/api/reports/gl-analysis'
      path: '/api/reports/gl-analysis'
      fullPath: '/api/reports/gl-analysis'
      preLoaderRoute: typeof ApiReportsGlAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills/update': {
      id: '/api/bills/update'
      path: '/api/bills/update'
      fullPath: '/api/bills/update'
      preLoaderRoute: typeof ApiBillsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills/create': {
      id: '/api/bills/create'
      path: '/api/bills/create'
      fullPath: '/api/bills/create'
      preLoaderRoute: typeof ApiBillsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev-connect': {
      id: '/api/auth/dev-connect'
      path: '/api/auth/dev-connect'
      fullPath: '/api/auth/dev-connect'
      preLoaderRoute: typeof ApiAuthDevConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevLoginRoute: DevLoginRoute,
  HistoryRoute: HistoryRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthDevConnectRoute: ApiAuthDevConnectRoute,
  ApiBillsCreateRoute: ApiBillsCreateRoute,
  ApiBillsUpdateRoute: ApiBillsUpdateRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiReportsGlAnalysisRoute: ApiReportsGlAnalysisRoute,
  PurchaseInvoicesIdEditRoute: PurchaseInvoicesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
