/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as ApiAuthDevConnectRouteImport } from './routes/api/auth/dev-connect'

const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevConnectRoute = ApiAuthDevConnectRouteImport.update({
  id: '/api/auth/dev-connect',
  path: '/api/auth/dev-connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/api/auth/dev-connect': typeof ApiAuthDevConnectRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev-login' | '/api/auth/dev-connect' | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev-login' | '/api/auth/dev-connect' | '/api/proxy/$'
  id: '__root__' | '/' | '/dev-login' | '/api/auth/dev-connect' | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevLoginRoute: typeof DevLoginRoute
  ApiAuthDevConnectRoute: typeof ApiAuthDevConnectRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev-connect': {
      id: '/api/auth/dev-connect'
      path: '/api/auth/dev-connect'
      fullPath: '/api/auth/dev-connect'
      preLoaderRoute: typeof ApiAuthDevConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevLoginRoute: DevLoginRoute,
  ApiAuthDevConnectRoute: ApiAuthDevConnectRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
